name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --unsafe-perm

      - name: Give Cypress executable permission
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run
