name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear Cypress cache
        run: rm -rf ~/.cache/Cypress

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --unsafe-perm

      - name: Install Cypress binary
        run: sudo npx cypress install

      - name: Run Cypress tests using GitHub Action
        uses: cypress-io/github-action@v2
        with:
          start: npm start
