name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and Cypress
        run: |
          npm install
          npx cypress install
          chmod +x ./node_modules/.bin/cypress
          npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run
